### PR TITLE
fix for hyperflow cutter

### PR DESCRIPTION
**Pull request by N-Maas**
ensure that the block weight is also valid for an imbalanced partition

### CODE REVIEW

**Comment by SebastianSchlag** [comment]
Do you know what the quality impact of this is?

**Comment by larsgottesbueren** [comment]
> Do you know what the quality impact of this is?

Quality shouldn't get worse because the FlowCutter code will converge faster to what it considers a feasible solution -- based on the max part weights it receives.

**Comment by larsgottesbueren** [comment]
Is this a fix for the runtime_error that the code throws in case the weight of the source or sink already exceeds the part weight? 
Or are there other errors that I should look into?
Either way, we should discuss what we actually want to happen, if the refinement receives an imbalanced partition. I think there are three options.
1) Skip refinement. Or balance the solution first, if possible, and then employ refinement
2) Try to balance the solution with whfc; only works if hg.partWeight(b0) + hg.partWeight(b1) <= max_part_weight[b0] + max_part_weight[b1]. Then we have to adapt the size constraint of the BFS searches, so that the source and target have weight <= max_part_weight as well.
3) Don't care about improving the balance, but we'd be happy if whfc accidentally manages it (if it does, it's with better or equal quality). Then this PR works fine.

Downside of 2) is obviously it doesn't always work, and may be slow because the instances are bigger.
I like option 1)

**Comment by N-Maas** [comment]
> Is this a fix for the runtime_error that the code throws in case the weight of the source or sink already exceeds the part weight?
> Or are there other errors that I should look into?

This is a fix for the runtime error. (The primary motivation here was that KaHyPar must terminate correctly even for imbalanced partitions, otherwise our experiments don't work.)

>     1. Skip refinement. Or balance the solution first, if possible, and then employ refinement

As soon as #70 is merged, initial partitioning will always return a balanced solution, if one can be (efficiently) found at all. I.e. balancing afterwards will not be possible, leaving only the option to skip refinement.

>     2. Try to balance the solution with whfc; only works if hg.partWeight(b0) + hg.partWeight(b1) <= max_part_weight[b0] + max_part_weight[b1]. Then we have to adapt the size constraint of the BFS searches, so that the source and target have weight <= max_part_weight as well.

I am not sure why wfc should even be able to improve the balance, if moving weights between two blocks suffices wouldn't the local search already find a balanced solution (apart from the coming IP balance guarantees)?

> I like option 1)

The question seems to be skipping or improving the solution even if it's imbalanced.

**Comment by larsgottesbueren** [comment]
If it's just to get the experiments running, then this is fine.
Maybe add a comment to the changed code.

If PR #70 fixes the issue altogether, we don't have to make a decision :)

**Comment by SebastianSchlag** [comment]
Thanks!

**Pull request merged**
